version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: ruf2xeceuraijahl1sheoh1ohW0fee5Eat8iy1Roh5roo5Iph3Pho4sel1il1uru
serial:
  port: tcp://192.168.88.43:6638
  adapter: zstack
  baudrate: 115200
  rtscts: true
advanced:
  log_level: info
  channel: 11
  network_key:
    - 66
    - 127
    - 50
    - 186
    - 209
    - 254
    - 153
    - 64
    - 185
    - 97
    - 93
    - 71
    - 216
    - 2
    - 126
    - 213
  pan_id: 42721
  ext_pan_id:
    - 166
    - 226
    - 201
    - 183
    - 122
    - 250
    - 35
    - 181
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
onboarding: true
